# Generated by Django 3.2.4 on 2021-06-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('apelido', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=40)),
                ('mensagem', models.TextField(max_length=4000)),
                ('criado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
