# Generated by Django 3.2.4 on 2021-07-03 20:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64)),
                ('duracao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r1', models.CharField(default=True, max_length=3)),
                ('r2', models.CharField(default=True, max_length=75)),
                ('r3', models.CharField(default=True, max_length=15)),
                ('r4', models.CharField(default=True, max_length=22)),
                ('r5', models.IntegerField(default=1)),
                ('r6', models.CharField(default=True, max_length=19)),
                ('r7', models.TextField(max_length=4000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('e1', models.IntegerField(blank=True, null=True)),
                ('r1', models.IntegerField(default=6)),
                ('cotacao1', models.IntegerField(default=0)),
                ('e2', models.IntegerField(blank=True, null=True)),
                ('r2', models.IntegerField(default=6)),
                ('cotacao2', models.IntegerField(default=0)),
                ('e3', models.CharField(blank=True, max_length=3, null=True)),
                ('r3', models.CharField(default='Si', max_length=3)),
                ('cotacao3', models.IntegerField(default=0)),
                ('e4', models.CharField(blank=True, max_length=52, null=True)),
                ('r4', models.CharField(default='Conjunto de notas ordernadas pela sua frequência/tom', max_length=52)),
                ('cotacao4', models.IntegerField(default=0)),
                ('e5', models.CharField(blank=True, max_length=43, null=True)),
                ('r5', models.CharField(default='Um conjunto harmónico de três ou mais notas', max_length=43)),
                ('cotacao5', models.IntegerField(default=0)),
                ('e6', models.CharField(blank=True, max_length=21, null=True)),
                ('r6', models.CharField(default='Trastes e casas', max_length=21)),
                ('cotacao6', models.IntegerField(default=0)),
                ('e7', models.DateField(blank=True, null=True)),
                ('r7', models.DateField(default=datetime.date(1997, 11, 28))),
                ('cotacao7', models.IntegerField(default=0)),
                ('e8', models.CharField(blank=True, max_length=9, null=True)),
                ('r8', models.CharField(default='sustenido', max_length=9)),
                ('cotacao8', models.IntegerField(default=0)),
                ('e9', models.CharField(blank=True, max_length=24, null=True)),
                ('r9', models.CharField(default='Mi, Lá, Ré, Sol, Si e Mi', max_length=24)),
                ('cotacao9', models.IntegerField(default=0)),
                ('e10', models.CharField(blank=True, max_length=39, null=True)),
                ('r10', models.CharField(default="['Slide', 'Bend', 'Dedilhado']", max_length=39)),
                ('cotacao10', models.IntegerField(default=0)),
                ('cotacaoglobal', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizes',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3)),
                ('designacao', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('apelido', models.CharField(max_length=64)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('data_nascimento', models.DateField()),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('aulas', models.ManyToManyField(blank=True, related_name='Contatos', to='website.Aula')),
            ],
        ),
        migrations.AddField(
            model_name='aula',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Salas', to='website.sala'),
        ),
    ]
