# Generated by Django 3.2.4 on 2021-06-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opiniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default=None, max_length=3, null=True, verbose_name='Foi a primeira vez que visitou o website?')),
            ],
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(max_length=40),
        ),
    ]
