# Generated by Django 3.2.4 on 2021-07-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='p1',
            field=models.CharField(default='1. Quantas cordas tem uma viola standard?', max_length=200),
        ),
        migrations.AddField(
            model_name='quiz',
            name='p10',
            field=models.CharField(default='10. Quais destas técnicas são de guitarra acústica?', max_length=200),
        ),
        migrations.AddField(
            model_name='quiz',
            name='p2',
            field=models.CharField(default='2. Qual o número da corda com a nota mais grave numa viola?', max_length=200),
        ),
        migrations.AddField(
            model_name='quiz',
            name='p3',
            field=models.CharField(default='3. Qual é a nota da segunda corda de uma viola?', max_length=200),
        ),
        migrations.AddField(
            model_name='quiz',
            name='p4',
            field=models.CharField(default='4. O que é Escala Músical?', max_length=200),
        ),
        migrations.AddField(
            model_name='quiz',
            name='p5',
            field=models.CharField(default='5. O que é um acorde?', max_length=200),
        ),
        migrations.AddField(
            model_name='quiz',
            name='p6',
            field=models.CharField(default='6. Quais os nome dados às partes que constituem o braço da viola?', max_length=200),
        ),
        migrations.AddField(
            model_name='quiz',
            name='p7',
            field=models.CharField(default='7. Qual a data de nascimento de Alexandr Misko, vencedor do prémio Guitarrista do Ano em 2018?', max_length=200),
        ),
        migrations.AddField(
            model_name='quiz',
            name='p8',
            field=models.CharField(default='8. Nos símbolos de acordes o que significa #?', max_length=200),
        ),
        migrations.AddField(
            model_name='quiz',
            name='p9',
            field=models.CharField(default='9. No 12º traste quais são as notas que podemos encontrar?', max_length=200),
        ),
    ]
