# Generated by Django 3.2.4 on 2021-06-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210610_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='opiniao',
            name='p2',
            field=models.CharField(choices=[(1, 'Pesquisa na web'), (2, 'Recomendado por um amigo(a)/familiar/colega'), (3, 'Outro')], default=True, max_length=43),
        ),
        migrations.AddField(
            model_name='opiniao',
            name='p3',
            field=models.CharField(choices=[(1, 'Sim, tudo'), (2, 'Sim, uma parte'), (3, 'Não, nada')], default=True, max_length=15),
        ),
        migrations.AddField(
            model_name='opiniao',
            name='p4',
            field=models.CharField(choices=[(1, 'Muito compreensíveis'), (2, 'Compremensíveis'), (3, 'Pouco compreensíveis'), (4, 'Incompreensíveis'), (5, 'Muito incompreensíveis')], default=True, max_length=22),
        ),
        migrations.AddField(
            model_name='opiniao',
            name='p5',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='opiniao',
            name='p6',
            field=models.CharField(choices=[(1, 'Definitivamente sim'), (2, 'Provavelmente sim'), (3, 'Não sei'), (4, 'Provavelmente não'), (5, 'Definitivamente não')], default=True, max_length=19),
        ),
        migrations.AddField(
            model_name='opiniao',
            name='p7',
            field=models.TextField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='opiniao',
            name='p1',
            field=models.CharField(choices=[('Sim', 'Sim'), (2, 'Não')], default=True, max_length=3),
        ),
    ]
