# Generated by Django 3.2.4 on 2021-06-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210612_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opiniao',
            name='p1',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='opiniao',
            name='p2',
            field=models.CharField(choices=[('Pesquisa na web', 'Pesquisa na web'), ('Recomendado por um amigo(a)/familiar/colega', 'Recomendado por um amigo(a)/familiar/colega'), ('Outro', 'Outro')], default=True, max_length=43),
        ),
        migrations.AlterField(
            model_name='opiniao',
            name='p3',
            field=models.CharField(choices=[('Sim, tudo', 'Sim, tudo'), ('Sim, uma parte', 'Sim, uma parte'), ('Não, nada', 'Não, nada')], default=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='opiniao',
            name='p4',
            field=models.CharField(choices=[('Muito compreensíveis', 'Muito compreensíveis'), ('Compreensíveis', 'Compreensíveis'), ('Pouco compreensíveis', 'Pouco compreensíveis'), ('Incompreensíveis', 'Incompreensíveis'), ('Muito incompreensíveis', 'Muito incompreensíveis')], default=True, max_length=22),
        ),
        migrations.AlterField(
            model_name='opiniao',
            name='p6',
            field=models.CharField(choices=[('Definitivamente sim', 'Definitivamente sim'), ('Provavelmente sim', 'Provavelmente sim'), ('Não sei', 'Não sei'), ('Provavelmente não', 'Provavelmente não'), ('Definitivamente não', 'Definitivamente não')], default=True, max_length=19),
        ),
    ]
