# Generated by Django 3.2.4 on 2021-06-12 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210612_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opiniao',
            name='p2',
        ),
        migrations.RemoveField(
            model_name='opiniao',
            name='p3',
        ),
        migrations.RemoveField(
            model_name='opiniao',
            name='p4',
        ),
        migrations.RemoveField(
            model_name='opiniao',
            name='p5',
        ),
        migrations.RemoveField(
            model_name='opiniao',
            name='p6',
        ),
        migrations.RemoveField(
            model_name='opiniao',
            name='p7',
        ),
    ]
