# Generated by Django 3.2.4 on 2021-06-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210612_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='opiniao',
            name='p2',
            field=models.CharField(choices=[('Pesquisa na web', 'Pesquisa na web'), ('Recomendado por um amigo(a)/familiar/colega', 'Recomendado por um amigo(a)/familiar/colega'), ('Outro', 'Outro')], default=True, max_length=43),
        ),
    ]
