# Generated by Django 3.2.4 on 2021-06-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210612_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='opiniao',
            name='p4',
            field=models.CharField(choices=[('Muito compreensíveis', 'Muito compreensíveis'), ('Compreensíveis', 'Compreensíveis'), ('Pouco compreensíveis', 'Pouco compreensíveis'), ('Incompreensíveis', 'Incompreensíveis'), ('Muito incompreensíveis', 'Muito incompreensíveis')], default=True, max_length=22),
        ),
    ]
