# Generated by Django 3.2.4 on 2021-06-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_opiniao_p4'),
    ]

    operations = [
        migrations.AddField(
            model_name='opiniao',
            name='p5',
            field=models.IntegerField(default=1),
        ),
    ]
