# Generated by Django 3.2.4 on 2021-06-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_opiniao_p2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opiniao',
            name='p2',
            field=models.CharField(choices=[('Pesquisa na web', 'Pesquisa na web'), ('Recomendado por um amigo(a)/familiar/colega', 'Recomendado por um amigo(a)/familiar/colega'), ('Outro', 'Outro')], max_length=255, null=True),
        ),
    ]
