# Generated by Django 3.2.4 on 2021-06-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_opiniao_p2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opiniao',
            name='p1',
            field=models.CharField(default=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='opiniao',
            name='p2',
            field=models.CharField(default=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='opiniao',
            name='p3',
            field=models.CharField(default=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='opiniao',
            name='p4',
            field=models.CharField(default=True, max_length=22),
        ),
        migrations.AlterField(
            model_name='opiniao',
            name='p6',
            field=models.CharField(default=True, max_length=19),
        ),
    ]
