# Generated by Django 3.2.4 on 2021-06-12 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_contato_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Opiniao',
            new_name='Comentario',
        ),
    ]
