# Generated by Django 3.2.4 on 2021-06-12 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_rename_opiniao_comentario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentario',
            new_name='Comentarios',
        ),
        migrations.RenameModel(
            old_name='Contato',
            new_name='Contatos',
        ),
    ]
