# Generated by Django 3.2.4 on 2021-06-12 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20210612_2118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentarios',
            new_name='Comentario',
        ),
        migrations.RenameModel(
            old_name='Contatos',
            new_name='Contato',
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='contato',
            options={'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
    ]
