# Generated by Django 3.2.4 on 2021-06-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_remove_contato_mensagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.IntegerField(default=1)),
                ('p2', models.CharField(default=True, max_length=2)),
                ('p3', models.CharField(default=True, max_length=3)),
                ('p4', models.CharField(default=True, max_length=52)),
                ('p5', models.CharField(default=True, max_length=43)),
                ('p6', models.CharField(default=True, max_length=21)),
                ('p7', models.CharField(default=True, max_length=5)),
                ('p8', models.TextField(max_length=9, null=True)),
                ('p9', models.TextField(max_length=24, null=True)),
                ('p10', models.CharField(max_length=24, null=True)),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
    ]
