# Generated by Django 3.2.4 on 2021-06-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='p9',
            field=models.TextField(default=True, max_length=24),
        ),
    ]
