# Generated by Django 3.2.4 on 2021-06-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_quiz_p9'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='p8',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='p9',
            field=models.CharField(default=True, max_length=24),
        ),
    ]
