# Generated by Django 3.2.4 on 2021-06-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20210613_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='p10',
            field=models.CharField(max_length=39, null=True),
        ),
    ]
