# Generated by Django 3.2.4 on 2021-06-13 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20210613_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='p1',
            new_name='r1',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='p2',
            new_name='r2',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='p3',
            new_name='r3',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='p4',
            new_name='r4',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='p5',
            new_name='r5',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='p6',
            new_name='r6',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='p7',
            new_name='r7',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='p1',
            new_name='r1',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='p10',
            new_name='r10',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='p2',
            new_name='r2',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='p3',
            new_name='r3',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='p4',
            new_name='r4',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='p5',
            new_name='r5',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='p6',
            new_name='r6',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='p7',
            new_name='r7',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='p8',
            new_name='r8',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='p9',
            new_name='r9',
        ),
    ]
