# Generated by Django 3.2.4 on 2021-06-14 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_aluno_aula_sala'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contato',
            options={},
        ),
    ]
