# Generated by Django 3.2.4 on 2021-06-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_auto_20210614_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='aula',
            field=models.ManyToManyField(blank=True, related_name='alunos', to='website.Aula'),
        ),
    ]
