# Generated by Django 3.2.4 on 2021-06-14 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_alter_aluno_aula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='aula',
            new_name='aulas',
        ),
    ]
