# Generated by Django 3.2.4 on 2021-06-26 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_rename_aula_aluno_aulas'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='aulas',
            field=models.ManyToManyField(blank=True, related_name='Contatos', to='website.Aula'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Salas', to='website.sala'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='apelido',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
